-- ═══════════════════════════════════════════════════════════
-- 🚀 CKC-OS COLLABORATIVE EDITOR SCHEMA (Idempotent / Safe to Re-run)
-- ═══════════════════════════════════════════════════════════

-- 1. Documents Table
CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY,
    content TEXT DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Line Locks Table
CREATE TABLE IF NOT EXISTS line_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id TEXT REFERENCES documents(id) ON DELETE CASCADE,
    line_number INTEGER NOT NULL,
    locked_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    user_name TEXT,
    color TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(document_id, line_number)
);

-- 3. Enable Realtime (safe: only add if not already a member)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'documents'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE documents;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'line_locks'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE line_locks;
  END IF;
END $$;

-- 4. RLS (Row Level Security)
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE line_locks ENABLE ROW LEVEL SECURITY;

-- 5. Policies (safe: drop existing before recreating)
DROP POLICY IF EXISTS "Allow authenticated access" ON documents;
DROP POLICY IF EXISTS "Allow authenticated access" ON line_locks;

CREATE POLICY "Allow authenticated access" ON documents
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated access" ON line_locks
    FOR ALL USING (auth.role() = 'authenticated');
